### ISSUE TITLE
Fix verification embed 

### ISSUE THREAD

**Issue by mmcmd** [mmcmd/verification-bot#15]
Currently it's set to 3 months, need to make it correspond with what is set in the json file

**Comment by vcidst** [comment]
I see that this is already checked with `verification_requirement_join` variable and there's a corresponding field in the JSON file as well. Is this issue resolved?

**Comment by mmcmd** [comment]
Hi vcidst, line 122 specifies that the account age is over 3 months so it has automatically been verified. It's just a matter of changing the value in the embed to a variable

**Comment by vcidst** [comment]
Got it, I'll make some formatting changes and fix this
