### ISSUE TITLE
Birthdayboy isn't gender-neutral!

### ISSUE THREAD

**Issue by vcidst** [mmcmd/verification-bot#18]
This is probably a non-issue, but there's a variable `birthdayboy` in the source.  What would be a gender-neutral version of it? `birthday_person` sounds very awkward

**Comment by mmcmd** [comment]
You do bring up a very good point - it would probably be best to just split it into two roles: birthday girl (https://en.m.wiktionary.org/wiki/birthday_girl) and the current birthday boy role. Honestly this never even crossed my mind, good thing you brought it up!

**Comment by vcidst** [comment]
On what basis should the roles be split? The variable `birthdayboy` is defined in the function parameter,

```
async def birthday(ctx, birthdayboy: discord.Member):
```

**Comment by mmcmd** [comment]
Probably best to make a second command for it

+birthdaygirl
and
+birthdayboy


Just realized you also wanted to include non-binary genders and although it's a good idea, I'm not certain there is a gender neutral version of birthday boy/girl

**Comment by vcidst** [comment]
Added a birthdaynerd version too as a gender-neutral thing. Gosh! Gender-ing is tough!

**Comment by mmcmd** [comment]
Solved in #17
