### ISSUE TITLE
When is birthday role removed?

### ISSUE THREAD

**Issue by vcidst** [mmcmd/verification-bot#21]
The source at one point messages `Gave the birthday boy role to <@{0}>. Automatically removing it in 12 hours`. However later it does `await asyncio.sleep(64800)`. That would put it to sleep for 64800 seconds which is 18 hours.

Shouldn't this instead be `12 hours * 3600 seconds/hour` (43200s)?

**Comment by mmcmd** [comment]
Correct, it initially was 12 hours, however I extended it to 18

**Comment by vcidst** [comment]
Why not 24 though?

**Comment by mmcmd** [comment]
I could make it 24, though often times the role will extend to the next day as it's not an automated process which gives the user the role (yet!) 

Future plans would be to automatically give the role out via a database entry that the user would submit

**Comment by mmcmd** [comment]
#17 solved this
